### ISSUE TITLE
Crashes on setup, can't find file. openssl missing on windows?

### ISSUE THREAD

**Issue by dny238** [vadimkantorov/wemosetup#3]
Do I need to install openssl on windows 10? 

C:\Users\robert.bruce\Downloads\wemosetup-master\wemosetup-master>wemosetup.py discover

Discovery of WeMo devices

Discovered:
 - WeMo Switch (10.22.22.1:49152)

C:\Users\robert.bruce\Downloads\wemosetup-master\wemosetup-master>wemosetup.py connecthomenetwork --ip 10.22.22.1 --port 49152 --ssid prettyflyforawifi --password notmypassword
Traceback (most recent call last):
  File "C:\Users\robert.bruce\Downloads\wemosetup-master\wemosetup-master\wemosetup.py", line 256, in <module>
    cmd(**args)
  File "C:\Users\robert.bruce\Downloads\wemosetup-master\wemosetup-master\wemosetup.py", line 135, in connecthomenetwork
    'password' : device.encrypt_wifi_password(password, meta_array),
  File "C:\Users\robert.bruce\Downloads\wemosetup-master\wemosetup-master\wemosetup.py", line 88, in encrypt_wifi_password
    stdout, stderr = subprocess.Popen(['openssl', 'enc', '-aes-128-cbc', '-md', 'md5', '-S', salt.encode('hex'), '-iv', iv.encode('hex'), '-pass', 'pass:' + keydata], stdin = subprocess.PIPE, stdout = subprocess.PIPE).communicate(password)
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by dny238** [comment]
Yup, after I installed OpenSSL and set it's path so it works, everything was good. 
Probably could include openssl.exe in the package? Or a better error message?

**Comment by vadimkantorov** [comment]
I thin it’s ok as is :) OpenSSL is listed as a dependency in documentation. If you wish to fix that, please send a PR.
