### ISSUE TITLE
encode hex no longer working in python3

### ISSUE THREAD

**Issue by disgustipated** [vadimkantorov/wemosetup#7]
Looks like the encode hex command in the encrypt_wifi_password is failing in python3 when trying to add a device. I tried importing codecs  and changing it to 
`codecs.encode(salt, 'hex')`
and 
`codecs.encode(iv,'hex')`

but it still seems to fail with it complaining about it being a string and not byte coded
``
Discovered 3 networks with SSID "wifissid", using the first available..."
Traceback (most recent call last):
  File "/usr/lib/python3.8/encodings/hex_codec.py", line 15, in hex_encode
    return (binascii.b2a_hex(input), len(input))
TypeError: a bytes-like object is required, not 'str'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "wemosetup.py", line 258, in <module>
    cmd(**args)
  File "wemosetup.py", line 137, in connecthomenetwork
    'password' : device.encrypt_wifi_password(password, meta_array),
  File "wemosetup.py", line 90, in encrypt_wifi_password
    stdout, stderr = subprocess.Popen(['openssl', 'enc', '-aes-128-cbc', '-md', 'md5', '-S', codecs.encode(salt, 'hex'), '-iv', codecs.encode(iv,'hex'), '-pass', 'pass:' + keydata], stdin = subprocess.PIPE, stdout = subprocess.PIPE).communicate(password)
TypeError: encoding with 'hex' codec failed (TypeError: a bytes-like object is required, not 'str')
``

I can poke through python a bit but not extremely versed in it so not sure what to try next.

**Comment by vadimkantorov** [comment]
you'd have to poke yourself, yes :(
you'd need to put in `.encode()` (or `.encode("utf-8")`, but i i'm not sure if anything there supports utf8) in right places to convert ascii strings to bytes

poking can be limited to that encrytpt_wifi_password function which is short

**Comment by disgustipated** [comment]
Are the salt and iv values required for wemo setup? looks like you can use just '-salt' with openssl and it will generate a random salt.

**Comment by vadimkantorov** [comment]
they are required, yes, you must use specific iv/salt that come the device metadata call

**Comment by deftdawg** [comment]
Any example of how we would do this?

**Comment by vadimkantorov** [comment]
I think the course of action should be: go over the code, check for bytes / strings arguments. If needed, find the commit before python2->python3 refactoring to see what it was supposed to be doing.

Sorry I'm not of help, but I don't have access to wemo devices anymore. But with some basic debugging and comparing to the old Python2 version, one should be able to do these fixes.

**Comment by h4km4k** [comment]
Fixed with my pull request:

[https://github.com/vadimkantorov/wemosetup/pull/8](https://github.com/vadimkantorov/wemosetup/pull/8)

**Comment by vadimkantorov** [comment]
@h4km4k merged

if you confirm it's fixed now, i could close the issue?

**Comment by h4km4k** [comment]
Just tried it with one switch and it worked. Yes.

Am 9. Februar 2025 23:02:54 MEZ schrieb Vadim Kantorov ***@***.***>:

**Comment by h4km4k** [comment]
These things are getting old and doesn't support things like WPA3, but that has nothing to do with your code.

Am 9. Februar 2025 23:02:54 MEZ schrieb Vadim Kantorov ***@***.***>:

**Comment by vadimkantorov** [comment]
the point of my script was to reverse-engineer the connecttohomenetwork... as regular switch-ons/offs were already handled by pywemo/ouimeaux...

but yeah, if it stopped working / can't be checked, I'm going to close this issue anyway. if the code is useful for anyone, they can check it to see how the connecttohomenetwork was being tone back then
